### ISSUE TITLE
searchItems method behavior no is the correct

### ISSUE THREAD

**Issue by CharlyJazz** [glpi-project/javascript-library-glpi#39]
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Support request => Please do not submit support request here, instead see https://github.com/glpi-project/javascript-library-glpi/blob/develop/CONTRIBUTING.md#questions-or-doubts

## Current behavior

The method `searchItems` is not creating the correct url to filter data with the criteria parameter
I think that problem is here in this [line](https://github.com/glpi-project/javascript-library-glpi/blob/f7a6eba357cef4a0b448a3fdc942f4a11644461f/src/prepareRequest.js#L11)

The createQueryString function doesn't name the criteria array as "criteria" instead ir recieves "items" as it's name.

The current url  is: 

`https://dev.flyve.org/glpi/apirest.php//search/computer/?items[0][field]=23&items[0][searchtype]=equal&items[0][value]=android&session_token=tokenexample`

And the expected is:

`https://dev.flyve.org/glpi/apirest.php//search/computer/?criteria[0][field]=23&criteria[0][searchtype]=equal&criteria[0][value]=android&session_token=tokenexample`

## Expected behavior

The server should return the correct data filtering

![image](https://user-images.githubusercontent.com/12489333/35546723-dab88d7c-054b-11e8-80e8-72ca81009389.png)

![image](https://user-images.githubusercontent.com/12489333/35546714-d098520a-054b-11e8-8034-cc97b0529a92.png)

## Minimal reproduction of the problem with instructions
  ```
  let query = [
      {
        "field":       23,
        "searchtype": "equal", // No equals, I dont know why...
        "value":      "android"
      }
    ]
    
    GlpiApi.searchItems('computer', query).then(function(value) {
      console.log(value) // Should return 1 item
    }, function(reason) {
      console.log(reason)
    });

```

**Comment by Gianfranco97** [comment]
@CharlyJazz thank you very much for the feedback my friend, we are already working to fix that

**Comment by Gianfranco97** [comment]
@CharlyJazz request built with its parameters

![captura de pantalla 2018-01-30 a la s 2 08 33 p m](https://user-images.githubusercontent.com/19965590/35583218-90af8cfe-05c7-11e8-9cc4-5ab578099b27.png)

**Comment by CharlyJazz** [comment]
@Gianfranco97 

I do not understand what you are trying to tell me
That is the url generated by searchItems?

**Comment by Gianfranco97** [comment]
@CharlyJazz no, I already fixed the library code. Give me a moment to assemble the PR
