### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by Gianfranco97** [glpi-project/javascript-library-glpi#51]
### Expected behavior:

Create a method to create and get a captcha.

To create:
- path = /PluginFlyvemdmdemoCaptcha
- method = POST
- body = `{"input": {}}`
- header 
  - Content-Type = application/json
  - Session-Token = {{sessionToken}}

To get: 
- path = /PluginFlyvemdmdemoCaptcha/:id?alt=media
- method = GET
- header 
  - Content-Type = application/octet-stream
  - Session-Token = {{sessionToken}}

**Comment by ajsb85** [comment]
**Reason:** `PluginFlyvemdmdemoCaptcha` is an Item Type specific of other projects.
