### ISSUE TITLE
Upload files

### ISSUE THREAD

**Issue by Gianfranco97** [glpi-project/javascript-library-glpi#57]
### Expected behavior:

Create a method to upload files in glpi. 

Documentation:

- https://dev.flyve.org/glpi/apirest.php#special-cases

references to upload a file with fetch: 

- https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API
- https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
- https://seamusleahy.com/submitting-a-form-with-the-fetch-api/
- https://stackoverflow.com/questions/36067767/how-do-i-upload-a-file-with-the-js-fetch-api

**Comment by Gianfranco97** [comment]
### Current Error: 


![captura de pantalla 2018-02-08 a la s 11 19 31 a m](https://user-images.githubusercontent.com/19965590/35980868-2e32a99c-0cc2-11e8-9cfd-bde269c974b5.png)
```js
["ERROR_UPLOAD_FILE_TOO_BIG_POST_MAX_SIZE","The file seems too big"]
```

**Request Headers:**

![captura de pantalla 2018-02-08 a la s 11 30 07 a m](https://user-images.githubusercontent.com/19965590/35981383-8210883a-0cc3-11e8-9782-5c8a18baf96c.png)


```
POST /apirest.php/Document?session_token=clp9ljruih9l4ddev6dimuao14 HTTP/1.1
Host: glpis42.local
Connection: keep-alive
Content-Length: 44718
Pragma: no-cache
Cache-Control: no-cache
accept: application/json
Origin: http://localhost:3000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
content-type: multipart/form-data
Referer: http://localhost:3000/app
Accept-Encoding: gzip, deflate
Accept-Language: en,es-419;q=0.9,es;q=0.8
DNT: 1
```



**Response Headers:**

![captura de pantalla 2018-02-08 a la s 11 28 25 a m](https://user-images.githubusercontent.com/19965590/35981280-40ad7eac-0cc3-11e8-8154-d5a4e6531481.png)

```
HTTP/1.1 400 Bad Request
Date: Thu, 08 Feb 2018 14:09:52 GMT
Server: Apache/2.4.12 (Ubuntu)
Pragma: no-cache
Access-Control-Allow-Origin: *
Cache-Control: no-store, no-cache, must-revalidate
Expires: Mon, 26 Jul 1997 05:00:00 GMT
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json; charset=UTF-8
```

**Comment by ajsb85** [comment]
Hi, @Gianfranco97 

Try increasing the following values in php.ini, for example:

memory_limit = 32M
upload_max_filesize = 24M
post_max_size = 32M

Could you @DIOHz0r  help Gianfranco in the office?

Thanks.

**Comment by ajsb85** [comment]
Hi, @Gianfranco97 

Here an example how to upload a file in Postman

![image](https://user-images.githubusercontent.com/663460/35983603-a1888a58-0cf2-11e8-88ca-42d2dbc21f19.png)

**Comment by btry** [comment]
The message may be misleading.

Please show the HTTP request body (not the answer)

**Comment by btry** [comment]
@Gianfranco97 

Read this 

https://github.com/glpi-project/glpi/blob/9.2/bugfixes/apirest.md#upload-a-document-file

**Comment by btry** [comment]
There is also the chunked file upload, which is not part of the API, available with the entry point 

```glpi/ajax/fileupload.php```

It is designed to work with a JQuery file upload compolent of the GLPI UI.

**Comment by Gianfranco97** [comment]
## My request:

**General**

![captura de pantalla 2018-02-08 a la s 3 51 34 p m](https://user-images.githubusercontent.com/19965590/35995105-caa35a08-0ce8-11e8-92e7-a57229492c45.png)

**Headers**

![captura de pantalla 2018-02-08 a la s 3 50 53 p m](https://user-images.githubusercontent.com/19965590/35995187-00e44c58-0ce9-11e8-9e6d-dd40b0c4dc8e.png)


**Payload**

![captura de pantalla 2018-02-08 a la s 3 48 04 p m](https://user-images.githubusercontent.com/19965590/35994662-84b2e136-0ce7-11e8-8eea-54694ef2540a.png)

## Response:

**Headers**

![captura de pantalla 2018-02-08 a la s 3 51 10 p m](https://user-images.githubusercontent.com/19965590/35995284-3bf88a98-0ce9-11e8-9123-66931cf60614.png)

**Body**

![captura de pantalla 2018-02-08 a la s 3 51 52 p m](https://user-images.githubusercontent.com/19965590/35995305-4de69a88-0ce9-11e8-89cc-99ad2ad70b83.png)

## My Code: 

```js
Object.keys(this.state.files).forEach((key) => {
     const file = this.state.files[key]
     formData.append('file', file)
     formData.append('uploadManifest',  `{"input": {"name": "${file.name}"}}`)
})

const glpi = new GLPI({url: 'http://glpis42.local/apirest.php'})
await glpi.initSessionByCredentials({userName: 'glpi', userPassword: 'glpi'})
await glpi.uploadFile({file: formData})
```

```js
let myHeaders = new Headers()
myHeaders.append('Content-Type', 'multipart/form-data')

const options = {
     method: 'POST',
     body: data.file,
     headers: myHeaders
}

fetch ('http://glpis42.local/apirest.php/PluginFlyvemdmFile', options)
.
.
.
```

**Comment by Gianfranco97** [comment]
It breaks in [this line](https://github.com/glpi-project/glpi/blob/9bfac06fd83efdd255d548a04a7b1a75f2db0100/inc/apirest.class.php#L401)   because supposedly, it does not receive any file.

The problem is that I have tried to send the file in different ways but none seems to work, I still do not know what I'm doing wrong.

**Comment by Gianfranco97** [comment]
I got it to work using XMLHttpRequest

```js
var req = new XMLHttpRequest()
req.open('POST', 'http://glpis42.local/apirest.php/PluginFlyvemdmFile', true)
req.setRequestHeader("Session-Token", "8oe2p0c6uducof68h1jbons3m6")
req.onreadystatechange = function (aEvt) {
    console.log(req)
}
req.send(formData)
```


I'm going to change all the requests from the library to this Api

**Comment by Gianfranco97** [comment]
### formData Example
```js
filesUpload = async () => {
   const formData = new FormData()
   Object.keys(this.state.files).forEach((key) => {
        const file = this.state.files[key]
        formData.append('file', file)
        formData.append('uploadManifest',  `{"input": {"name": "${file.name}"}}`)
.
.
.
```

**Comment by Biruk-Amlaku** [comment]
The problem is with adding the header content-type: multipart/form-data without a boundary. Remove that header and it' should work just fine.
