### ISSUE TITLE
Documentation on how to use may be incorrect

### ISSUE THREAD

**Issue by finalbeta** [glpi-project/javascript-library-glpi#77]
His, this is likely a failure on my side to comprehend how this is used. 

The documentation said there are no external dependencies to use this javascript library. 
It shows "import Glpi from '@glpi-project/javascript-library-glpi';"
@ does not seems to be standard javascript? Are other tools required to use this project?

**Comment by Gianfranco97** [comment]
'@glpi-project' is the organization in npm in which the library is located, this is perfectly normal.

If you review the project's package you can appreciate that there is no dependence for its operation.

- https://github.com/glpi-project/javascript-library-glpi/blob/develop/package.json
